/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.iniciartransporte;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FuncionarioModel;
import model.VeiculoModel;
import model.crt.EncomendaModel;
import model.crt.FreteModel;
import model.crt.FretexEncomendaModel;
import repository.EmpresaRepository;
import repository.EncomendaRepository;
import repository.FreteRepository;
import repository.FretexEncomendaRepository;
import repository.FuncionarioRepository;
import repository.VeiculoRepository;

/**
 *
 * @author Frank
 */
public class frameFinalizar extends javax.swing.JInternalFrame {

    private static frameFinalizar frameFinalizar;
    private EncomendaRepository encomendaRepository = null;
    private VeiculoRepository veiculoRepository = null;
    private FuncionarioRepository funcionarioRepository = null;
    private FretexEncomendaRepository fretexEncomendaRepository = null;
    private FreteRepository freteRepository = null;
    private EmpresaRepository empresaRepository = null;

    public static frameFinalizar getInstancia() {
        if (frameFinalizar == null) {
            frameFinalizar = new frameFinalizar();
        }
        return frameFinalizar;
    }

    public frameFinalizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public class ComboItem {

        private String value;
        private String label;

        public ComboItem(String value, String label) {
            this.value = value;
            this.label = label;
        }

        public String getValue() {
            return this.value;
        }

        public String getLabel() {
            return this.label;
        }

        @Override
        public String toString() {
            return label;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTitulo2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeBuscar = new javax.swing.JTextField();
        botaoBuscarCargos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtableFrete = new javax.swing.JTable();
        botaoGerarMICDTA = new javax.swing.JButton();
        btnGerarCRT = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Finalizar Frete");
        setToolTipText("FinalizarFrete");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setVisible(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(56, 65, 84));

        jLabel1.setBackground(new java.awt.Color(56, 65, 84));
        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Finalizar Frete");
        jLabel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        labelTitulo2.setBackground(new java.awt.Color(56, 65, 84));
        labelTitulo2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        labelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo2.setText("Fretes Já Cadastrados e Já Finalizados");
        labelTitulo2.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel4.setText("Nome");

        botaoBuscarCargos.setBackground(new java.awt.Color(0, 204, 153));
        botaoBuscarCargos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoBuscarCargos.setForeground(new java.awt.Color(255, 255, 255));
        botaoBuscarCargos.setText("Buscar");
        botaoBuscarCargos.setBorder(null);
        botaoBuscarCargos.setBorderPainted(false);
        botaoBuscarCargos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoBuscarCargos.setPreferredSize(new java.awt.Dimension(43, 20));
        botaoBuscarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarCargosActionPerformed(evt);
            }
        });

        jtableFrete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Motorista", "Veículo", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtableFrete.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(jtableFrete);
        jtableFrete.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtableFrete.getColumnModel().getColumnCount() > 0) {
            jtableFrete.getColumnModel().getColumn(0).setMinWidth(0);
            jtableFrete.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtableFrete.getColumnModel().getColumn(0).setMaxWidth(0);
            jtableFrete.getColumnModel().getColumn(1).setMinWidth(200);
            jtableFrete.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtableFrete.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTitulo2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(botaoBuscarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBuscarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        botaoGerarMICDTA.setBackground(new java.awt.Color(0, 51, 51));
        botaoGerarMICDTA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoGerarMICDTA.setForeground(new java.awt.Color(255, 255, 255));
        botaoGerarMICDTA.setText("Gerar MIC/DTA");
        botaoGerarMICDTA.setBorderPainted(false);
        botaoGerarMICDTA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoGerarMICDTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoGerarMICDTAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoGerarMICDTAMouseExited(evt);
            }
        });
        botaoGerarMICDTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarMICDTAActionPerformed(evt);
            }
        });

        btnGerarCRT.setBackground(new java.awt.Color(0, 51, 51));
        btnGerarCRT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGerarCRT.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarCRT.setText("Gerar CRT");
        btnGerarCRT.setBorderPainted(false);
        btnGerarCRT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGerarCRT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGerarCRTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGerarCRTMouseExited(evt);
            }
        });
        btnGerarCRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarCRTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoGerarMICDTA, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(btnGerarCRT, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(botaoGerarMICDTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGerarCRT)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void populaTabelaFretes() {
        if (this.freteRepository == null) {
            this.freteRepository = new FreteRepository();
        }
        DefaultTableModel model = (DefaultTableModel) jtableFrete.getModel();
        model.setRowCount(0);
        List<FreteModel> listaDeFretes = this.freteRepository.buscarTodos();
        for (int i = 0; i < listaDeFretes.size(); i++) {
            model.addRow(new Object[]{
                listaDeFretes.get(i).getIdFrete(),
                listaDeFretes.get(i).getMotorista().getNome(),
                listaDeFretes.get(i).getVeiculo().getModelo() + "/" +listaDeFretes.get(i).getVeiculo().getPlacaCarreta(),
                listaDeFretes.get(i).getObservacao()
            });
        }
        jtableFrete.setModel(model);
    }
        
    private void botaoGerarMICDTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarMICDTAActionPerformed
        int linhaSelecionada = jtableFrete.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro");
        } else {
            long idFrete = (long) jtableFrete.getValueAt(linhaSelecionada, 0);
            DefaultTableModel dtm = (DefaultTableModel) jtableFrete.getModel();
            FreteModel freteModel = this.freteRepository.buscarPorId(idFrete);
            //EncomendaModel encomendaModel = this.encomendaRepository.buscarPorId(freteModel.getid)
        }
    }//GEN-LAST:event_botaoGerarMICDTAActionPerformed

    private void btnGerarCRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarCRTActionPerformed
        int linhaSelecionada = jtableFrete.getSelectedRow();;;
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro");
        } else {
            long idFrete = (long) jtableFrete.getValueAt(linhaSelecionada, 0);
            int retorno = JOptionPane.showConfirmDialog(null, "Gostaria realmente de excluir o registro selecionado?", "Alerta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (retorno == 0) {
                DefaultTableModel dtm = (DefaultTableModel) jtableFrete.getModel();
                FreteModel frete = this.freteRepository.buscarPorId(idFrete);
                this.freteRepository.excluir(frete);
                dtm.removeRow(jtableFrete.getSelectedRow());
                jtableFrete.setModel(dtm);
            }
        }
    }//GEN-LAST:event_btnGerarCRTActionPerformed

    private void botaoGerarMICDTAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGerarMICDTAMouseEntered
        botaoGerarMICDTA.setBackground(new Color(255, 255, 20));
        botaoGerarMICDTA.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoGerarMICDTAMouseEntered

    private void botaoGerarMICDTAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGerarMICDTAMouseExited
        botaoGerarMICDTA.setBackground(new Color(0, 51, 51));
        botaoGerarMICDTA.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoGerarMICDTAMouseExited

    private void btnGerarCRTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarCRTMouseEntered
        btnGerarCRT.setBackground(new Color(255, 255, 20));
        btnGerarCRT.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnGerarCRTMouseEntered

    private void btnGerarCRTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarCRTMouseExited
        btnGerarCRT.setBackground(new Color(0, 51, 51));
        btnGerarCRT.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnGerarCRTMouseExited

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (this.encomendaRepository != null) {
            this.encomendaRepository.fecharConexao();
        }
        if (this.freteRepository != null) {
            this.freteRepository.fecharConexao();
        }
        if (this.veiculoRepository != null) {
            this.veiculoRepository.fecharConexao();
        }
        if (this.funcionarioRepository != null) {
            this.funcionarioRepository.fecharConexao();
        }
        if (this.fretexEncomendaRepository != null) {
            this.fretexEncomendaRepository.fecharConexao();
        }
        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosing

    private void botaoBuscarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarCargosActionPerformed
        populaTabelaFretes();
    }//GEN-LAST:event_botaoBuscarCargosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarCargos;
    private javax.swing.JButton botaoGerarMICDTA;
    private javax.swing.JButton btnGerarCRT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtableFrete;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JTextField txtNomeBuscar;
    // End of variables declaration//GEN-END:variables
}
