/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.iniciartransporte;

import view.pessoa.*;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CargoModel;
import model.EmpresaModel;
import model.VolumeModel;
import model.crt.EncomendaModel;
import model.crt.EncomendaxVolumeModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import repository.CargoRepository;
import repository.EmpresaRepository;
import repository.EncomendaRepository;
import repository.EncomendaxVolumeRepository;
import repository.VolumeRepository;

/**
 *
 * @author Frank
 */
public class frameEncomenda extends javax.swing.JInternalFrame {

    private static frameEncomenda frameEncomenda;
    private EncomendaRepository encomendaRepository = null;
    private VolumeRepository volumeRepository = null;
    private EmpresaRepository empresaRepository = null;
    private EncomendaxVolumeRepository encomendaxVolumeRepository = null;

    public static frameEncomenda getInstancia() {
        if (frameEncomenda == null) {
            frameEncomenda = new frameEncomenda();
        }
        return frameEncomenda;
    }

    public frameEncomenda() {
        initComponents();
        //((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        botaoCancelarEdicao.setVisible(false);
        txtIdEncomenda.setVisible(false);
        populaComboBoxRemetente(null);
        populaComboBoxDestinatario(null);
        populaComboBoxVolumes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public class ComboItem {

        private String value;
        private String label;

        public ComboItem(String value, String label) {
            this.value = value;
            this.label = label;
        }

        public String getValue() {
            return this.value;
        }

        public String getLabel() {
            return this.label;
        }

        @Override
        public String toString() {
            return label;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTitulo2 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtableVolumesRelacionados = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNomeBuscar = new javax.swing.JTextField();
        botaoBuscarCargos = new javax.swing.JButton();
        txtIdEncomenda = new javax.swing.JTextField();
        comboBoxDestinatario = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboBoxVolume = new javax.swing.JComboBox<>();
        comboBoxRemetente = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtableEncomendas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        btnRelacionar = new javax.swing.JButton();
        botaoCadastrarCargo = new javax.swing.JButton();
        botaoEditarRegistro = new javax.swing.JButton();
        botaoRemoverRegistro = new javax.swing.JButton();
        botaoCancelarEdicao = new javax.swing.JButton();
        botaoGerarRelatorio = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Encomenda");
        setToolTipText("Cadastro de Encomenda");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setVisible(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(56, 65, 84));

        jLabel1.setBackground(new java.awt.Color(56, 65, 84));
        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Criar Encomenda");
        jLabel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        labelTitulo2.setBackground(new java.awt.Color(56, 65, 84));
        labelTitulo2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        labelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo2.setText("Encomendas Já Cadastrados e Não Finalizadas");
        labelTitulo2.setRequestFocusEnabled(false);

        labelTitulo.setBackground(new java.awt.Color(56, 65, 84));
        labelTitulo.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Encomenda");
        labelTitulo.setRequestFocusEnabled(false);

        jtableVolumesRelacionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtableVolumesRelacionados.setColumnSelectionAllowed(true);
        jtableVolumesRelacionados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jtableVolumesRelacionados);
        jtableVolumesRelacionados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtableVolumesRelacionados.getColumnModel().getColumnCount() > 0) {
            jtableVolumesRelacionados.getColumnModel().getColumn(0).setMinWidth(0);
            jtableVolumesRelacionados.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtableVolumesRelacionados.getColumnModel().getColumn(0).setMaxWidth(0);
            jtableVolumesRelacionados.getColumnModel().getColumn(1).setMinWidth(200);
            jtableVolumesRelacionados.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtableVolumesRelacionados.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel4.setText("Nome");

        botaoBuscarCargos.setBackground(new java.awt.Color(0, 204, 153));
        botaoBuscarCargos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoBuscarCargos.setForeground(new java.awt.Color(255, 255, 255));
        botaoBuscarCargos.setText("Buscar");
        botaoBuscarCargos.setBorder(null);
        botaoBuscarCargos.setBorderPainted(false);
        botaoBuscarCargos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoBuscarCargos.setPreferredSize(new java.awt.Dimension(43, 20));
        botaoBuscarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarCargosActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel10.setText("Destinatário");

        jLabel12.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel12.setText("Descrição");

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel13.setText("Remetente");

        jtableEncomendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Remetente", "Destinatário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtableEncomendas.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(jtableEncomendas);
        jtableEncomendas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtableEncomendas.getColumnModel().getColumnCount() > 0) {
            jtableEncomendas.getColumnModel().getColumn(0).setMinWidth(0);
            jtableEncomendas.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtableEncomendas.getColumnModel().getColumn(0).setMaxWidth(0);
            jtableEncomendas.getColumnModel().getColumn(1).setMinWidth(200);
            jtableEncomendas.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtableEncomendas.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel5.setText("Peso");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane2.setViewportView(txtDescricao);

        jLabel14.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel14.setText("Volume");

        btnRelacionar.setText("Relacionar");
        btnRelacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelacionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIdEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(labelTitulo2)
                        .addGap(254, 254, 254))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(comboBoxRemetente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                        .addGap(249, 249, 249)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(51, 51, 51)
                                                .addComponent(btnRelacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(14, 14, 14))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(comboBoxVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoBuscarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboBoxVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRelacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBuscarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoCadastrarCargo.setBackground(new java.awt.Color(0, 51, 51));
        botaoCadastrarCargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCadastrarCargo.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrarCargo.setText("Salvar");
        botaoCadastrarCargo.setBorder(null);
        botaoCadastrarCargo.setBorderPainted(false);
        botaoCadastrarCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCadastrarCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCadastrarCargoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCadastrarCargoMouseExited(evt);
            }
        });
        botaoCadastrarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarCargoActionPerformed(evt);
            }
        });

        botaoEditarRegistro.setBackground(new java.awt.Color(0, 51, 51));
        botaoEditarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEditarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botaoEditarRegistro.setText("Editar Registro");
        botaoEditarRegistro.setBorderPainted(false);
        botaoEditarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoEditarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoEditarRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoEditarRegistroMouseExited(evt);
            }
        });
        botaoEditarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarRegistroActionPerformed(evt);
            }
        });

        botaoRemoverRegistro.setBackground(new java.awt.Color(0, 51, 51));
        botaoRemoverRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoRemoverRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botaoRemoverRegistro.setText("Remover Registro");
        botaoRemoverRegistro.setBorderPainted(false);
        botaoRemoverRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoRemoverRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoRemoverRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoRemoverRegistroMouseExited(evt);
            }
        });
        botaoRemoverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverRegistroActionPerformed(evt);
            }
        });

        botaoCancelarEdicao.setBackground(new java.awt.Color(0, 51, 51));
        botaoCancelarEdicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCancelarEdicao.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelarEdicao.setText("Cancelar Alteração");
        botaoCancelarEdicao.setBorder(null);
        botaoCancelarEdicao.setBorderPainted(false);
        botaoCancelarEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCancelarEdicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCancelarEdicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCancelarEdicaoMouseExited(evt);
            }
        });
        botaoCancelarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarEdicaoActionPerformed(evt);
            }
        });

        botaoGerarRelatorio.setBackground(new java.awt.Color(0, 51, 51));
        botaoGerarRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoGerarRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        botaoGerarRelatorio.setText("Gerar Relatório");
        botaoGerarRelatorio.setBorderPainted(false);
        botaoGerarRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoGerarRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoGerarRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoGerarRelatorioMouseExited(evt);
            }
        });
        botaoGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrarCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEditarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(botaoRemoverRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(botaoCancelarEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(botaoCadastrarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoCancelarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addComponent(botaoEditarRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemoverRegistro)
                        .addGap(27, 27, 27)
                        .addComponent(botaoGerarRelatorio)
                        .addGap(131, 131, 131))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populaComboBoxRemetente(EmpresaModel empresaSelecionada) {
        if (this.empresaRepository == null) {
            this.empresaRepository = new EmpresaRepository();
        }
        List<EmpresaModel> listaDeEmpresas = this.empresaRepository.buscarTodos();
        Object objs[] = new Object[listaDeEmpresas.size()];
        frameEncomenda.ComboItem item;
        int itemSelecionado = 0;
        //objs[0] = new ComboItem("0", "Selecione");
        for (int i = 0; i < listaDeEmpresas.size(); i++) {
            item = new ComboItem("" + listaDeEmpresas.get(i).getIdEmpresa(), listaDeEmpresas.get(i).getNomeFantasia());
            objs[i] = item;
            if (empresaSelecionada != null) {
                if (empresaSelecionada.getNomeFantasia().toLowerCase().trim().equals(listaDeEmpresas.get(i).getNomeFantasia().toLowerCase().trim())) {
                    itemSelecionado = i;
                }
            }
        }
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(objs);
        comboBoxRemetente.setModel(model2);
        if (empresaSelecionada != null) {
            comboBoxRemetente.setSelectedIndex(itemSelecionado);
        }
    }
    
    private void populaComboBoxDestinatario(EmpresaModel empresaSelecionada) {
        if (this.empresaRepository == null) {
            this.empresaRepository = new EmpresaRepository();
        }
        List<EmpresaModel> listaDeEmpresas = this.empresaRepository.buscarTodos();
        Object objs[] = new Object[listaDeEmpresas.size()];
        frameEncomenda.ComboItem item;
        int itemSelecionado = 0;
        //objs[0] = new ComboItem("0", "Selecione");
        for (int i = 0; i < listaDeEmpresas.size(); i++) {
            item = new ComboItem("" + listaDeEmpresas.get(i).getIdEmpresa(), listaDeEmpresas.get(i).getNomeFantasia());
            objs[i] = item;
            if (empresaSelecionada != null) {
                if (empresaSelecionada.getNomeFantasia().toLowerCase().trim().equals(listaDeEmpresas.get(i).getNomeFantasia().toLowerCase().trim())) {
                    itemSelecionado = i;
                }
            }
        }
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(objs);
        comboBoxDestinatario.setModel(model2);
        if (empresaSelecionada != null) {
            comboBoxDestinatario.setSelectedIndex(itemSelecionado);
        }
    }
    
    private void populaComboBoxVolumes() {
        if (this.volumeRepository == null) {
            this.volumeRepository = new VolumeRepository();
        }
        List<VolumeModel> listaDeVolumes = this.volumeRepository.buscarTodos();
        Object objs[] = new Object[listaDeVolumes.size()];
        frameEncomenda.ComboItem item;
        for (int i = 0; i < listaDeVolumes.size(); i++) {
            item = new frameEncomenda.ComboItem("" + listaDeVolumes.get(i).getIdVolume(), listaDeVolumes.get(i).getNome());
            objs[i] = item;
        }
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(objs);
        comboBoxVolume.setModel(model2);
    }
    
    private void populaTabelaEncomendas() {
        if (this.encomendaRepository == null) {
            this.encomendaRepository = new EncomendaRepository();
        }
        DefaultTableModel model = (DefaultTableModel) jtableEncomendas.getModel();
        model.setRowCount(0);
        List<EncomendaModel> listaDeEncomendas = this.encomendaRepository.buscarTodos();
        for (int i = 0; i < listaDeEncomendas.size(); i++) {
            model.addRow(new Object[]{
                listaDeEncomendas.get(i).getIdEncomenda(),
                listaDeEncomendas.get(i).getRemetente().getNomeFantasia(),
                listaDeEncomendas.get(i).getDestinatario().getNomeFantasia()
            });
        }
        jtableEncomendas.setModel(model);
    }
    
     private void populaTabelaVolumesRelacionados(Long idEncomenda) {
        if (this.encomendaxVolumeRepository == null) {
            this.encomendaxVolumeRepository = new EncomendaxVolumeRepository();
        }
        DefaultTableModel model = (DefaultTableModel) jtableVolumesRelacionados.getModel();
        model.setRowCount(0);
        List<EncomendaxVolumeModel> listaDeVolumesRelacionados = this.encomendaxVolumeRepository.buscarPorEncomenda(idEncomenda);
        for (int i = 0; i < listaDeVolumesRelacionados.size(); i++) {
            model.addRow(new Object[]{
                listaDeVolumesRelacionados.get(i).getIdEncomendaxVolume(),
                listaDeVolumesRelacionados.get(i).getVolume().getNome(),
                listaDeVolumesRelacionados.get(i).getDescricaoProduto()
            });
        }
        jtableVolumesRelacionados.setModel(model);
    }

    private void botaoCadastrarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarCargoActionPerformed
       /* if (!txtNomeCargo.getText().equals("") && !txtDescricaoCargo.getText().equals("")) {
            CargoModel cargo = new CargoModel();
            cargo.setNome(txtNomeCargo.getText());
            cargo.setDescricao(txtDescricaoCargo.getText());
            if (!txtIdEncomenda.getText().equals("")) {
                long idCargo;
                idCargo = Long.parseLong(txtIdEncomenda.getText());
                cargo.setIdCargo(idCargo);
            }
            if (this.empresaRepository == null) {
                this.empresaRepository = new CargoRepository();
            }

            try {
                if (!txtIdEncomenda.getText().equals("")) {
                    this.empresaRepository.atualizar(cargo);
                } else {
                    this.empresaRepository.salvar(cargo);
                }
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            txtNomeCargo.setText("");
            txtDescricaoCargo.setText("");
            txtIdEncomenda.setText("");
            botaoCancelarEdicao.setVisible(false);
            botaoCadastrarCargo.setLabel("Salvar");
        } else {
            JOptionPane.showMessageDialog(null, "Informe o nome e a descrição do cargo");
        }*/
    }//GEN-LAST:event_botaoCadastrarCargoActionPerformed

    private void botaoCadastrarCargoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarCargoMouseEntered
        botaoCadastrarCargo.setBackground(new Color(0, 153, 0));
        botaoCadastrarCargo.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoCadastrarCargoMouseEntered
    
    private void botaoCadastrarCargoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarCargoMouseExited
        botaoCadastrarCargo.setBackground(new Color(0, 51, 51));
        botaoCadastrarCargo.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoCadastrarCargoMouseExited

    private void botaoBuscarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarCargosActionPerformed
        populaTabelaEncomendas();
    }//GEN-LAST:event_botaoBuscarCargosActionPerformed
    
    private void botaoEditarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarRegistroActionPerformed
        int linhaSelecionada = jtableEncomendas.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro");
        } else {
            long idEncomenda = (long) jtableEncomendas.getValueAt(linhaSelecionada, 0);
            DefaultTableModel dtm = (DefaultTableModel) jtableEncomendas.getModel();
            EncomendaModel encomendaModel = this.encomendaRepository.buscarPorId(idEncomenda);
            
            populaTabelaVolumesRelacionados(encomendaModel.getIdEncomenda());
            
            txtIdEncomenda.setText(encomendaModel.getIdEncomenda()+"");
            
            populaComboBoxDestinatario(encomendaModel.getDestinatario());
            populaComboBoxRemetente(encomendaModel.getRemetente());
            
            comboBoxDestinatario.setEnabled(false);
            comboBoxRemetente.setEnabled(false);
            
            botaoCancelarEdicao.setVisible(true);
            botaoCadastrarCargo.setLabel("Salvar Alteração");
        }
    }//GEN-LAST:event_botaoEditarRegistroActionPerformed

    private void botaoRemoverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroActionPerformed
        int linhaSelecionada = jtableEncomendas.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro");
        } else {
            long idEncomenda = (long) jtableEncomendas.getValueAt(linhaSelecionada, 0);
            int retorno = JOptionPane.showConfirmDialog(null, "Gostaria realmente de excluir o registro selecionado?", "Alerta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (retorno == 0) {
                DefaultTableModel dtm = (DefaultTableModel) jtableEncomendas.getModel();
                EncomendaModel encomenda = this.encomendaRepository.buscarPorId(idEncomenda);
                this.encomendaRepository.excluir(encomenda);
                dtm.removeRow(jtableEncomendas.getSelectedRow());
                jtableEncomendas.setModel(dtm);
            }
        }
    }//GEN-LAST:event_botaoRemoverRegistroActionPerformed

    private void botaoEditarRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarRegistroMouseEntered
        botaoEditarRegistro.setBackground(new Color(204, 204, 0));
        botaoEditarRegistro.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoEditarRegistroMouseEntered

    private void botaoEditarRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarRegistroMouseExited
        botaoEditarRegistro.setBackground(new Color(0, 51, 51));
        botaoEditarRegistro.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoEditarRegistroMouseExited

    private void botaoRemoverRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroMouseEntered
        botaoRemoverRegistro.setBackground(new Color(255, 51, 51));
        botaoRemoverRegistro.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoRemoverRegistroMouseEntered

    private void botaoRemoverRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroMouseExited
        botaoRemoverRegistro.setBackground(new Color(0, 51, 51));
        botaoRemoverRegistro.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoRemoverRegistroMouseExited

    private void botaoCancelarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarEdicaoActionPerformed
        txtIdEncomenda.setText("");
        txtDescricao.setText("");
        txtPeso.setText("");
        
        DefaultTableModel model = (DefaultTableModel) jtableVolumesRelacionados.getModel();
        model.setRowCount(0);
        jtableVolumesRelacionados.setModel(model);
        
        comboBoxDestinatario.setEnabled(true);
        comboBoxRemetente.setEnabled(true);
        comboBoxDestinatario.setSelectedIndex(0);
        comboBoxRemetente.setSelectedIndex(0);
        comboBoxVolume.setSelectedIndex(0);
        botaoCancelarEdicao.setVisible(false);
        botaoCadastrarCargo.setLabel("Salvar");
    }//GEN-LAST:event_botaoCancelarEdicaoActionPerformed

    private void botaoCancelarEdicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCancelarEdicaoMouseEntered
        botaoCancelarEdicao.setBackground(new Color(204, 204, 0));
        botaoCancelarEdicao.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoCancelarEdicaoMouseEntered

    private void botaoCancelarEdicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCancelarEdicaoMouseExited
        botaoCancelarEdicao.setBackground(new Color(0, 51, 51));
        botaoCancelarEdicao.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoCancelarEdicaoMouseExited

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (this.encomendaRepository != null) {
            this.encomendaRepository.fecharConexao();
        }
        if (this.encomendaxVolumeRepository != null) {
            this.encomendaxVolumeRepository.fecharConexao();
        }
        if (this.empresaRepository != null) {
            this.empresaRepository.fecharConexao();
        }
        if (this.volumeRepository != null) {
            this.volumeRepository.fecharConexao();
        }
        txtIdEncomenda.setText("");
        botaoCancelarEdicao.setVisible(false);
        botaoCadastrarCargo.setLabel("Salvar");

        DefaultTableModel model = (DefaultTableModel) jtableVolumesRelacionados.getModel();
        model.setRowCount(0);
        jtableVolumesRelacionados.setModel(model);

        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosing

    private void botaoGerarRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGerarRelatorioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoGerarRelatorioMouseEntered

    private void botaoGerarRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGerarRelatorioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoGerarRelatorioMouseExited

    private void botaoGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelatorioActionPerformed
        /*List<CargoModel> listaCargos = cargoRepository.buscarPorNome("chefão");
        JasperPrint jasperPrint = null;
        String path = "resources/jasperreports/cargos2.jrxml";
        
        try {
            InputStream employeeReportStream;
            employeeReportStream = new FileInputStream(new File(path).getPath());
            JasperReport jasperReport = JasperCompileManager.compileReport(employeeReportStream);
            JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(listaCargos);
            jasperPrint = JasperFillManager.fillReport(jasperReport, null, ds);
        } catch (FileNotFoundException | JRException ex) {
            Logger.getLogger(frameEncomenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_botaoGerarRelatorioActionPerformed

    private void btnRelacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelacionarActionPerformed
        if (!txtDescricao.getText().equals("") && !txtPeso.getText().equals("")) {
            EncomendaModel encomendaModel = new EncomendaModel();
            ComboItem item;
            if (txtIdEncomenda.getText().equals("")){
                if (this.encomendaRepository == null) {
                    this.encomendaRepository = new EncomendaRepository();
                }
                if (this.empresaRepository == null) {
                    this.empresaRepository = new EmpresaRepository();
                }

                item = (ComboItem) comboBoxRemetente.getSelectedItem();
                long remetenteID = Long.parseLong(item.getValue());
                EmpresaModel remetente = empresaRepository.buscarPorId(remetenteID);

                item = (ComboItem) comboBoxDestinatario.getSelectedItem();
                long destinatarioID = Long.parseLong(item.getValue());
                EmpresaModel destinatario = empresaRepository.buscarPorId(destinatarioID);

                encomendaModel.setDestinatario(destinatario);
                encomendaModel.setRemetente(remetente);
                encomendaModel.setFinalizada(false);

                encomendaRepository.salvar(encomendaModel);
                
                txtIdEncomenda.setText(encomendaModel.getIdEncomenda()+"");
            }else{
                encomendaModel = encomendaRepository.buscarPorId(Long.parseLong(txtIdEncomenda.getText()));
            }
            
            if (this.encomendaxVolumeRepository == null) {
                this.encomendaxVolumeRepository = new EncomendaxVolumeRepository();
            }
            if (this.volumeRepository == null) {
                this.volumeRepository = new VolumeRepository();
            }
            
            EncomendaxVolumeModel encomendaxVolumeModel = new EncomendaxVolumeModel();
            encomendaxVolumeModel.setDescricaoProduto(txtDescricao.getText());
            encomendaxVolumeModel.setPesototal(Float.parseFloat(txtPeso.getText()));
            encomendaxVolumeModel.setFinalizada(false);
            
            item = (ComboItem) comboBoxVolume.getSelectedItem();
            long volumeID = Long.parseLong(item.getValue());
            VolumeModel volume = volumeRepository.buscarPorId(volumeID);
            encomendaxVolumeModel.setVolume(volume);
            
            encomendaxVolumeModel.setEncomenda(encomendaModel);
           
            encomendaxVolumeRepository.salvar(encomendaxVolumeModel);
           
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
           
            //txtIdEncomenda.setText("");
            populaTabelaVolumesRelacionados(encomendaModel.getIdEncomenda());
            
            encomendaModel = null;
            encomendaxVolumeModel = null;
            botaoCancelarEdicao.setVisible(false);
            botaoCadastrarCargo.setLabel("Salvar");
            comboBoxDestinatario.setEnabled(false);
            comboBoxRemetente.setEnabled(false);
            comboBoxVolume.setSelectedIndex(0);
            txtDescricao.setText("");
            txtPeso.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Informe o Peso e a Descrição");
        }
    }//GEN-LAST:event_btnRelacionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarCargos;
    private javax.swing.JButton botaoCadastrarCargo;
    private javax.swing.JButton botaoCancelarEdicao;
    private javax.swing.JButton botaoEditarRegistro;
    private javax.swing.JButton botaoGerarRelatorio;
    private javax.swing.JButton botaoRemoverRegistro;
    private javax.swing.JButton btnRelacionar;
    private javax.swing.JComboBox<String> comboBoxDestinatario;
    private javax.swing.JComboBox<String> comboBoxRemetente;
    private javax.swing.JComboBox<String> comboBoxVolume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtableEncomendas;
    private javax.swing.JTable jtableVolumesRelacionados;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtIdEncomenda;
    private javax.swing.JTextField txtNomeBuscar;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
