/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.iniciartransporte;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FuncionarioModel;
import model.VeiculoModel;
import model.crt.EncomendaModel;
import model.crt.FreteModel;
import model.crt.FretexEncomendaModel;
import repository.EncomendaRepository;
import repository.FreteRepository;
import repository.FretexEncomendaRepository;
import repository.FuncionarioRepository;
import repository.VeiculoRepository;

/**
 *
 * @author Frank
 */
public class frameFrete extends javax.swing.JInternalFrame {

    private static frameFrete frameFrete;
    private EncomendaRepository encomendaRepository = null;
    private VeiculoRepository veiculoRepository = null;
    private FuncionarioRepository funcionarioRepository = null;
    private FretexEncomendaRepository fretexEncomendaRepository = null;
    private FreteRepository freteRepository = null;

    public static frameFrete getInstancia() {
        if (frameFrete == null) {
            frameFrete = new frameFrete();
        }
        return frameFrete;
    }

    public frameFrete() {
        initComponents();
        //((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        botaoCancelarEdicao.setVisible(false);
        txtidFrete.setVisible(false);
        populaComboBoxMotorista(null);
        populaComboBoxVeiculo(null);
        populaComboBoxEncomendas();
        btnFinalizarEncomenda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public class ComboItem {

        private String value;
        private String label;

        public ComboItem(String value, String label) {
            this.value = value;
            this.label = label;
        }

        public String getValue() {
            return this.value;
        }

        public String getLabel() {
            return this.label;
        }

        @Override
        public String toString() {
            return label;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTitulo2 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtableEncomendasRelacionadas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNomeBuscar = new javax.swing.JTextField();
        botaoBuscarCargos = new javax.swing.JButton();
        txtidFrete = new javax.swing.JTextField();
        comboBoxVeiculo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboBoxEncomenda = new javax.swing.JComboBox<>();
        comboBoxMotorista = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtableFrete = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            txtData = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        btnRelacionar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtValorFrete = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtValorReembolso = new javax.swing.JTextField();
        botaoEditarRegistro = new javax.swing.JButton();
        botaoRemoverRegistro = new javax.swing.JButton();
        botaoCancelarEdicao = new javax.swing.JButton();
        btnFinalizarEncomenda = new javax.swing.JButton();
        botaoRemoverRegistroEncomenda = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Frete");
        setToolTipText("Cadastro de Frete");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setVisible(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(56, 65, 84));

        jLabel1.setBackground(new java.awt.Color(56, 65, 84));
        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Criar Frete");
        jLabel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        labelTitulo2.setBackground(new java.awt.Color(56, 65, 84));
        labelTitulo2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        labelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo2.setText("Fretes Já Cadastrados e Não Finalizados");
        labelTitulo2.setRequestFocusEnabled(false);

        labelTitulo.setBackground(new java.awt.Color(56, 65, 84));
        labelTitulo.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Frete");
        labelTitulo.setRequestFocusEnabled(false);

        jtableEncomendasRelacionadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Remetente", "Destinatario", "Valor Frete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtableEncomendasRelacionadas.setColumnSelectionAllowed(true);
        jtableEncomendasRelacionadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jtableEncomendasRelacionadas);
        jtableEncomendasRelacionadas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtableEncomendasRelacionadas.getColumnModel().getColumnCount() > 0) {
            jtableEncomendasRelacionadas.getColumnModel().getColumn(0).setMinWidth(0);
            jtableEncomendasRelacionadas.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtableEncomendasRelacionadas.getColumnModel().getColumn(0).setMaxWidth(0);
            jtableEncomendasRelacionadas.getColumnModel().getColumn(1).setMinWidth(200);
            jtableEncomendasRelacionadas.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtableEncomendasRelacionadas.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel4.setText("Nome");

        botaoBuscarCargos.setBackground(new java.awt.Color(0, 204, 153));
        botaoBuscarCargos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoBuscarCargos.setForeground(new java.awt.Color(255, 255, 255));
        botaoBuscarCargos.setText("Buscar");
        botaoBuscarCargos.setBorder(null);
        botaoBuscarCargos.setBorderPainted(false);
        botaoBuscarCargos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoBuscarCargos.setPreferredSize(new java.awt.Dimension(43, 20));
        botaoBuscarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarCargosActionPerformed(evt);
            }
        });

        comboBoxVeiculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBoxVeiculoFocusGained(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel10.setText("Veículo");

        jLabel12.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel12.setText("Observação");

        comboBoxEncomenda.setMaximumSize(new java.awt.Dimension(28, 20));
        comboBoxEncomenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBoxEncomendaFocusGained(evt);
            }
        });

        comboBoxMotorista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBoxMotoristaFocusGained(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel13.setText("Motorista");

        jtableFrete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Motorista", "Veículo", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtableFrete.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(jtableFrete);
        jtableFrete.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtableFrete.getColumnModel().getColumnCount() > 0) {
            jtableFrete.getColumnModel().getColumn(0).setMinWidth(0);
            jtableFrete.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtableFrete.getColumnModel().getColumn(0).setMaxWidth(0);
            jtableFrete.getColumnModel().getColumn(1).setMinWidth(200);
            jtableFrete.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtableFrete.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel5.setText("Encomenda");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane2.setViewportView(txtObservacao);

        jLabel14.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel14.setText("Previsão Saída");

        btnRelacionar.setText("Relacionar");
        btnRelacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelacionarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel15.setText("R$ Frete");

        jLabel16.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel16.setText("R$ Reembolso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTitulo2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoBuscarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtidFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(67, 67, 67))
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comboBoxEncomenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValorReembolso, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRelacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel10)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(btnRelacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(30, 30, 30))
                                    .addComponent(txtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(txtValorReembolso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(labelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBuscarCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoEditarRegistro.setBackground(new java.awt.Color(0, 51, 51));
        botaoEditarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoEditarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botaoEditarRegistro.setText("Editar Registro");
        botaoEditarRegistro.setBorderPainted(false);
        botaoEditarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoEditarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoEditarRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoEditarRegistroMouseExited(evt);
            }
        });
        botaoEditarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarRegistroActionPerformed(evt);
            }
        });

        botaoRemoverRegistro.setBackground(new java.awt.Color(0, 51, 51));
        botaoRemoverRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoRemoverRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botaoRemoverRegistro.setText("Remover Registro");
        botaoRemoverRegistro.setBorderPainted(false);
        botaoRemoverRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoRemoverRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoRemoverRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoRemoverRegistroMouseExited(evt);
            }
        });
        botaoRemoverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverRegistroActionPerformed(evt);
            }
        });

        botaoCancelarEdicao.setBackground(new java.awt.Color(0, 51, 51));
        botaoCancelarEdicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCancelarEdicao.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelarEdicao.setText("Cancelar Alteração");
        botaoCancelarEdicao.setBorder(null);
        botaoCancelarEdicao.setBorderPainted(false);
        botaoCancelarEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCancelarEdicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCancelarEdicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCancelarEdicaoMouseExited(evt);
            }
        });
        botaoCancelarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarEdicaoActionPerformed(evt);
            }
        });

        btnFinalizarEncomenda.setBackground(new java.awt.Color(0, 51, 51));
        btnFinalizarEncomenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFinalizarEncomenda.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarEncomenda.setText("Finalizar Encomenda");
        btnFinalizarEncomenda.setBorder(null);
        btnFinalizarEncomenda.setBorderPainted(false);
        btnFinalizarEncomenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFinalizarEncomenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinalizarEncomendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinalizarEncomendaMouseExited(evt);
            }
        });
        btnFinalizarEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarEncomendaActionPerformed(evt);
            }
        });

        botaoRemoverRegistroEncomenda.setBackground(new java.awt.Color(0, 51, 51));
        botaoRemoverRegistroEncomenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoRemoverRegistroEncomenda.setForeground(new java.awt.Color(255, 255, 255));
        botaoRemoverRegistroEncomenda.setText("Remover Registro");
        botaoRemoverRegistroEncomenda.setBorderPainted(false);
        botaoRemoverRegistroEncomenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoRemoverRegistroEncomenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoRemoverRegistroEncomendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoRemoverRegistroEncomendaMouseExited(evt);
            }
        });
        botaoRemoverRegistroEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverRegistroEncomendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoEditarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(botaoRemoverRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(botaoCancelarEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizarEncomenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoRemoverRegistroEncomenda, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnFinalizarEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoCancelarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(botaoRemoverRegistroEncomenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoEditarRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRemoverRegistro)
                        .addGap(115, 115, 115))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populaComboBoxMotorista(FuncionarioModel funcionarioSelecionado) {
        if (this.funcionarioRepository == null) {
            this.funcionarioRepository = new FuncionarioRepository();
        }
        List<FuncionarioModel> listaDeFuncionarios = this.funcionarioRepository.buscarTodosMotorista();
        Object objs[] = new Object[listaDeFuncionarios.size()];
        frameFrete.ComboItem item;
        int itemSelecionado = 0;
        
        for (int i = 0; i < listaDeFuncionarios.size(); i++) {
            item = new ComboItem("" + listaDeFuncionarios.get(i).getIdPessoa(), listaDeFuncionarios.get(i).getNome());
            objs[i] = item;
            if (funcionarioSelecionado != null) {
                if (funcionarioSelecionado.getNome().toLowerCase().trim().equals(listaDeFuncionarios.get(i).getNome().toLowerCase().trim())) {
                    itemSelecionado = i;
                }
            }
        }
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(objs);
        comboBoxMotorista.setModel(model2);
        if (funcionarioSelecionado != null) {
            comboBoxMotorista.setSelectedIndex(itemSelecionado);
        }
    }
    
    private void populaComboBoxVeiculo(VeiculoModel veiculoSelecionado) {
        if (this.veiculoRepository == null) {
            this.veiculoRepository = new VeiculoRepository();
        }
        List<VeiculoModel> listaDeVeiculos = this.veiculoRepository.buscarTodos();
        Object objs[] = new Object[listaDeVeiculos.size()];
        frameFrete.ComboItem item;
        int itemSelecionado = 0;
        //objs[0] = new ComboItem("0", "Selecione");
        for (int i = 0; i < listaDeVeiculos.size(); i++) {
            item = new ComboItem("" + listaDeVeiculos.get(i).getIdVeiculo(), listaDeVeiculos.get(i).getModelo() + " / " + listaDeVeiculos.get(i).getPlacaCavalo());
            objs[i] = item;
            if (veiculoSelecionado != null) {
                if (veiculoSelecionado.getChassi().toLowerCase().trim().equals(listaDeVeiculos.get(i).getChassi().toLowerCase().trim())) {
                    itemSelecionado = i;
                }
            }
        }
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(objs);
        comboBoxVeiculo.setModel(model2);
        if (veiculoSelecionado != null) {
            comboBoxVeiculo.setSelectedIndex(itemSelecionado);
        }
    }
    
    private void populaComboBoxEncomendas() {
        if (this.encomendaRepository == null) {
            this.encomendaRepository = new EncomendaRepository();
        }
        List<EncomendaModel> listaDeEncomendas = this.encomendaRepository.buscarTodos();
        Object objs[] = new Object[listaDeEncomendas.size()];
        frameFrete.ComboItem item;
        for (int i = 0; i < listaDeEncomendas.size(); i++) {
            item = new frameFrete.ComboItem("" + listaDeEncomendas.get(i).getIdEncomenda(), listaDeEncomendas.get(i).getRemetente().getNomeFantasia() +" / "+listaDeEncomendas.get(i).getDestinatario().getNomeFantasia());
            objs[i] = item;
        }
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(objs);
        comboBoxEncomenda.setModel(model2);
    }
    
    private void populaTabelaFretes() {
        if (this.freteRepository == null) {
            this.freteRepository = new FreteRepository();
        }
        DefaultTableModel model = (DefaultTableModel) jtableFrete.getModel();
        model.setRowCount(0);
        List<FreteModel> listaDeFretes = this.freteRepository.buscarTodos();
        for (int i = 0; i < listaDeFretes.size(); i++) {
            model.addRow(new Object[]{
                listaDeFretes.get(i).getIdFrete(),
                listaDeFretes.get(i).getMotorista().getNome(),
                listaDeFretes.get(i).getVeiculo().getModelo() + "/" +listaDeFretes.get(i).getVeiculo().getPlacaCarreta(),
                listaDeFretes.get(i).getObservacao()
            });
        }
        jtableFrete.setModel(model);
    }
    
     private void populaTabelaEncomendasRelacionadas(Long idFrete) {
        if (this.fretexEncomendaRepository == null) {
            this.fretexEncomendaRepository = new FretexEncomendaRepository();
        }
        DefaultTableModel model = (DefaultTableModel) jtableEncomendasRelacionadas.getModel();
        model.setRowCount(0);
        List<FretexEncomendaModel> listaDeEncomendasRelacionadas = this.fretexEncomendaRepository.buscarPorFrete(idFrete);
        for (int i = 0; i < listaDeEncomendasRelacionadas.size(); i++) {
            model.addRow(new Object[]{
                listaDeEncomendasRelacionadas.get(i).getIdFretexEncomenda(),
                listaDeEncomendasRelacionadas.get(i).getEncomenda().getRemetente().getNomeFantasia(),
                listaDeEncomendasRelacionadas.get(i).getEncomenda().getDestinatario().getNomeFantasia(),
                listaDeEncomendasRelacionadas.get(i).getValorFrete()
            });
        }
        jtableEncomendasRelacionadas.setModel(model);
    }
        
    private void botaoEditarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarRegistroActionPerformed
        int linhaSelecionada = jtableFrete.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro");
        } else {
            long idFrete = (long) jtableFrete.getValueAt(linhaSelecionada, 0);
            DefaultTableModel dtm = (DefaultTableModel) jtableFrete.getModel();
            FreteModel freteModel = this.freteRepository.buscarPorId(idFrete);
            
            populaTabelaEncomendasRelacionadas(freteModel.getIdFrete());
            
            txtidFrete.setText(freteModel.getIdFrete()+"");
          
            SimpleDateFormat formatoDesejado = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = null;
            dataFormatada = formatoDesejado.format(freteModel.getPrevisaoSaida());
                    
            txtObservacao.setText(freteModel.getObservacao());
            txtData.setText(dataFormatada);
            populaComboBoxMotorista(freteModel.getMotorista());
            populaComboBoxVeiculo(freteModel.getVeiculo());
            
            comboBoxMotorista.setEnabled(false);
            comboBoxVeiculo.setEnabled(false);
            txtData.setEnabled(false);
            txtObservacao.setEnabled(false);
            comboBoxEncomenda.setEnabled(false);
            txtValorFrete.setEnabled(false);
            txtValorReembolso.setEnabled(false);
            btnRelacionar.setEnabled(false);
            
            comboBoxEncomenda.setSelectedIndex(0);
            txtValorFrete.setText("");
            txtValorReembolso.setText("");
            
            botaoCancelarEdicao.setVisible(true);
            btnFinalizarEncomenda.setVisible(true);
        }
    }//GEN-LAST:event_botaoEditarRegistroActionPerformed

    private void botaoRemoverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroActionPerformed
        int linhaSelecionada = jtableFrete.getSelectedRow();;;
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro");
        } else {
            long idFrete = (long) jtableFrete.getValueAt(linhaSelecionada, 0);
            int retorno = JOptionPane.showConfirmDialog(null, "Gostaria realmente de excluir o registro selecionado?", "Alerta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (retorno == 0) {
                DefaultTableModel dtm = (DefaultTableModel) jtableFrete.getModel();
                FreteModel frete = this.freteRepository.buscarPorId(idFrete);
                frete.setEhExcluido(true);
                freteRepository.atualizar(frete);
                dtm.removeRow(jtableFrete.getSelectedRow());
                jtableFrete.setModel(dtm);
            }
        }
    }//GEN-LAST:event_botaoRemoverRegistroActionPerformed

    private void botaoEditarRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarRegistroMouseEntered
        botaoEditarRegistro.setBackground(new Color(204, 204, 0));
        botaoEditarRegistro.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoEditarRegistroMouseEntered

    private void botaoEditarRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarRegistroMouseExited
        botaoEditarRegistro.setBackground(new Color(0, 51, 51));
        botaoEditarRegistro.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoEditarRegistroMouseExited

    private void botaoRemoverRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroMouseEntered
        botaoRemoverRegistro.setBackground(new Color(255, 51, 51));
        botaoRemoverRegistro.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoRemoverRegistroMouseEntered

    private void botaoRemoverRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroMouseExited
        botaoRemoverRegistro.setBackground(new Color(0, 51, 51));
        botaoRemoverRegistro.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoRemoverRegistroMouseExited

    private void botaoCancelarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarEdicaoActionPerformed
        txtidFrete.setText("");
        txtObservacao.setText("");
        txtData.setText("");
        txtObservacao.setText("");
        
        txtValorFrete.setText("");
        txtValorReembolso.setText("");
        DefaultTableModel model = (DefaultTableModel) jtableEncomendasRelacionadas.getModel();
        model.setRowCount(0);
        jtableEncomendasRelacionadas.setModel(model);
        
        btnFinalizarEncomenda.setVisible(false);
        comboBoxMotorista.setEnabled(true);
        comboBoxVeiculo.setEnabled(true);
        txtData.setEnabled(true);
        txtObservacao.setEnabled(true);
        comboBoxEncomenda.setEnabled(true);
        txtValorFrete.setEnabled(true);
        txtValorReembolso.setEnabled(true);
        btnRelacionar.setEnabled(true);
        comboBoxMotorista.setSelectedIndex(0);
        
        comboBoxVeiculo.setEnabled(true);
        comboBoxVeiculo.setSelectedIndex(0);
        
        comboBoxEncomenda.setEnabled(true);
        comboBoxEncomenda.setSelectedIndex(0);
        
        botaoCancelarEdicao.setVisible(false);
    }//GEN-LAST:event_botaoCancelarEdicaoActionPerformed

    private void botaoCancelarEdicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCancelarEdicaoMouseEntered
        botaoCancelarEdicao.setBackground(new Color(204, 204, 0));
        botaoCancelarEdicao.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoCancelarEdicaoMouseEntered

    private void botaoCancelarEdicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCancelarEdicaoMouseExited
        botaoCancelarEdicao.setBackground(new Color(0, 51, 51));
        botaoCancelarEdicao.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoCancelarEdicaoMouseExited

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (this.encomendaRepository != null) {
            this.encomendaRepository.fecharConexao();
        }
        if (this.freteRepository != null) {
            this.freteRepository.fecharConexao();
        }
        if (this.veiculoRepository != null) {
            this.veiculoRepository.fecharConexao();
        }
        if (this.funcionarioRepository != null) {
            this.funcionarioRepository.fecharConexao();
        }
        if (this.fretexEncomendaRepository != null) {
            this.fretexEncomendaRepository.fecharConexao();
        }
        
        txtidFrete.setText("");
        botaoCancelarEdicao.setVisible(false);
        
        DefaultTableModel model = (DefaultTableModel) jtableEncomendasRelacionadas.getModel();
        model.setRowCount(0);
        jtableEncomendasRelacionadas.setModel(model);
        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnRelacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelacionarActionPerformed
        if (!txtObservacao.getText().equals("") && !txtData.getText().equals("")) {
            if (this.freteRepository == null) {
                this.freteRepository = new FreteRepository();
            }
            FreteModel freteModel = new FreteModel();
            ComboItem item;
            if (txtidFrete.getText().equals("")){
                if (this.veiculoRepository== null) {
                    this.veiculoRepository = new VeiculoRepository();
                }
                if (this.funcionarioRepository == null) {
                    this.funcionarioRepository = new FuncionarioRepository();
                }
                
                item = (ComboItem) comboBoxMotorista.getSelectedItem();
                long motoristaId = Long.parseLong(item.getValue());
                FuncionarioModel funcionario = funcionarioRepository.buscarPorId(motoristaId);

                item = (ComboItem) comboBoxVeiculo.getSelectedItem();
                long veiculoId = Long.parseLong(item.getValue());
                VeiculoModel veiculoModel = veiculoRepository.buscarPorId(veiculoId);

                freteModel.setMotorista(funcionario);
                freteModel.setVeiculo(veiculoModel);
                freteModel.setFinalizada(false);
                freteModel.setObservacao(txtObservacao.getText());
                
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date dataFormatada = null;
                try { 
                    dataFormatada = formato.parse(txtData.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(frameFrete.class.getName()).log(Level.SEVERE, null, ex);
                }
                freteModel.setPrevisaoSaida(dataFormatada);
                
                this.freteRepository.salvar(freteModel);

                txtidFrete.setText(freteModel.getIdFrete()+"");
            }else{
                freteModel = freteRepository.buscarPorId(Long.parseLong(txtidFrete.getText()));
            }
            
            if (this.fretexEncomendaRepository == null) {
                this.fretexEncomendaRepository = new FretexEncomendaRepository();
            }
            if (this.encomendaRepository == null) {
                this.encomendaRepository = new EncomendaRepository();
            }

            FretexEncomendaModel fretexEncomendaModel = new FretexEncomendaModel();
            
            if(txtValorFrete.getText().equals("")){
                fretexEncomendaModel.setValorFrete(0);
            }else {
                fretexEncomendaModel.setValorFrete(Float.parseFloat(txtValorFrete.getText()));
            }
            
            if(txtValorReembolso.getText().equals("")){
                fretexEncomendaModel.setValorReembolso(0);
            }else {
                fretexEncomendaModel.setValorReembolso(Float.parseFloat(txtValorReembolso.getText()));
            }
            
            fretexEncomendaModel.setFinalizada(false);

            item = (ComboItem) comboBoxEncomenda.getSelectedItem();
            long encomendaID = Long.parseLong(item.getValue());
            EncomendaModel encomenda = encomendaRepository.buscarPorId(encomendaID);
            fretexEncomendaModel.setEncomenda(encomenda);

            fretexEncomendaModel.setFrete(freteModel);

            fretexEncomendaRepository.salvar(fretexEncomendaModel);

            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");


            populaTabelaEncomendasRelacionadas(freteModel.getIdFrete());

            freteModel = null;
            fretexEncomendaModel = null;
            botaoCancelarEdicao.setVisible(false);
            btnFinalizarEncomenda.setVisible(true);
            comboBoxVeiculo.setEnabled(false);
            comboBoxMotorista.setEnabled(false);
            txtData.setEnabled(false);
            txtObservacao.setEnabled(false);
            comboBoxEncomenda.setSelectedIndex(0);
            txtValorFrete.setText("");
            txtValorReembolso.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Informe a data e a observação");
        }
    }//GEN-LAST:event_btnRelacionarActionPerformed

    private void botaoBuscarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarCargosActionPerformed
        populaTabelaFretes();
    }//GEN-LAST:event_botaoBuscarCargosActionPerformed

    private void btnFinalizarEncomendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarEncomendaMouseEntered
        btnFinalizarEncomenda.setBackground(new Color(0, 153, 0));
        btnFinalizarEncomenda.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnFinalizarEncomendaMouseEntered

    private void btnFinalizarEncomendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarEncomendaMouseExited
        btnFinalizarEncomenda.setBackground(new Color(0, 51, 51));
        btnFinalizarEncomenda.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnFinalizarEncomendaMouseExited

    private void btnFinalizarEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarEncomendaActionPerformed
        if (this.fretexEncomendaRepository == null) {
            this.fretexEncomendaRepository = new FretexEncomendaRepository();
        }
        if (this.freteRepository == null) {
            this.freteRepository = new FreteRepository();
        }
        
        FreteModel freteModel = new FreteModel();
        freteModel = freteRepository.buscarPorId(Long.parseLong(txtidFrete.getText()));
        List<FretexEncomendaModel> listaDeFretesxEncomendas = fretexEncomendaRepository.buscarPorFrete(freteModel.getIdFrete());
        FretexEncomendaModel fretexEncomendaModel = new FretexEncomendaModel();

        for(int i = 0; i < listaDeFretesxEncomendas.size(); i++){
            fretexEncomendaModel = listaDeFretesxEncomendas.get(i);
            fretexEncomendaModel.setFinalizada(true);
            fretexEncomendaRepository.atualizar(fretexEncomendaModel);
        }

        freteModel.setFinalizada(true);
        freteRepository.atualizar(freteModel);

        DefaultTableModel model = (DefaultTableModel) jtableFrete.getModel();
        model.setRowCount(0);
        jtableFrete.setModel(model);

        btnFinalizarEncomenda.setVisible(false);
        botaoCancelarEdicaoActionPerformed(evt);
        freteModel = null;
    }//GEN-LAST:event_btnFinalizarEncomendaActionPerformed

    private void comboBoxMotoristaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxMotoristaFocusGained
        populaComboBoxMotorista(null);
    }//GEN-LAST:event_comboBoxMotoristaFocusGained

    private void comboBoxVeiculoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxVeiculoFocusGained
        populaComboBoxVeiculo(null);
    }//GEN-LAST:event_comboBoxVeiculoFocusGained

    private void comboBoxEncomendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxEncomendaFocusGained
        populaComboBoxEncomendas();
    }//GEN-LAST:event_comboBoxEncomendaFocusGained

    private void botaoRemoverRegistroEncomendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroEncomendaMouseEntered
        botaoRemoverRegistroEncomenda.setBackground(new Color(204, 204, 0));
        botaoRemoverRegistroEncomenda.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_botaoRemoverRegistroEncomendaMouseEntered

    private void botaoRemoverRegistroEncomendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroEncomendaMouseExited
        botaoRemoverRegistroEncomenda.setBackground(new Color(0, 51, 51));
        botaoRemoverRegistroEncomenda.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_botaoRemoverRegistroEncomendaMouseExited

    private void botaoRemoverRegistroEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverRegistroEncomendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRemoverRegistroEncomendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarCargos;
    private javax.swing.JButton botaoCancelarEdicao;
    private javax.swing.JButton botaoEditarRegistro;
    private javax.swing.JButton botaoRemoverRegistro;
    private javax.swing.JButton botaoRemoverRegistroEncomenda;
    private javax.swing.JButton btnFinalizarEncomenda;
    private javax.swing.JButton btnRelacionar;
    private javax.swing.JComboBox<String> comboBoxEncomenda;
    private javax.swing.JComboBox<String> comboBoxMotorista;
    private javax.swing.JComboBox<String> comboBoxVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtableEncomendasRelacionadas;
    private javax.swing.JTable jtableFrete;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNomeBuscar;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtValorFrete;
    private javax.swing.JTextField txtValorReembolso;
    private javax.swing.JTextField txtidFrete;
    // End of variables declaration//GEN-END:variables
}
